version: '3'

services:
  db: 
    image: postgres:17
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: cont_sebites_db
    volumes:
      - ./postgres:/var/lib/postgresql/data